### ISSUE TITLE
Add Leaderboard campaign cache

### ISSUE THREAD

**Issue by moisses89** [safe-global/safe-locking-service#117]
# What is needed?
Campaign leaderboard will change more or less in a weekly basis, that means have a cache of 1 minute is not the better solution. 
We would like to add cache for 5 days and be able to invalidate this cache when the activitys campaign data is updated.

**Comment by fmrsabino** [comment]
@moisses89 We should probably consider not tackling this if https://github.com/safe-global/safe-locking-service/pull/128 is merged. With a Materialized View we do have the end results of the query available and I find that the need for a cache here (plus invalidation) might create more complexity than required. The only cost that we'd incur would be on serialisation (from objects to JSON).

We can maybe even consider removing `@cache_page` completely https://github.com/safe-global/safe-locking-service/blob/c187e6e4e3a35b2a51e42f804485db88a0cad4b2/safe_locking_service/campaigns/views.py#L188

**Comment by moisses89** [comment]
I agree to don´t add more complexity with custom cache for this endpoint, but I would leave the `cache_page` because even we have a materialized view without cache every endpoint call will execute a SQL query to the database. 
I mean, I would leave the `cache_page` because is not complicating the code and is protecting us from some performance issues with the database.
