### ISSUE TITLE
Add an endpoint to return period points. 

### ISSUE THREAD

**Issue by moisses89** [safe-global/safe-locking-service#131]
# What is needed?
Add a GET endpoint for a campaign and address that return a list of period points. 

GET /api/v1/campaign/{resourceID}/periods/{address}

# Response 
To Be Defined

**Comment by fmrsabino** [comment]
One issue with the `address` path position on the endpoint is that it might look like we are doing a selection on the `Period` (i.e., "give me all periods that have this address"). 

`GET /api/v1/campaign/{resourceID}/periods/{address}`

My suggestion would be to do the selection on the address in the path:

`GET /api/v1/campaigns/{resourceID}/addresses/{address}/periods`

This way, I think it's more clear that the endpoint should return all periods for the provided `address`.

**Comment by fmrsabino** [comment]
I'd suggest the following schema. It'd be a paginated response and each result item represents the points for an `address` for a period (of a campaign with `resourceId`).

```javascript
GET /api/v1/campaigns/{resourceId}/addresses/{address}/periods

{
  "count": <number>,
  "next": <url>, // nullable
  "previous": <url>,  // nullable
  "results": [
    {
      "startDate": <string>, // date string e.g.: 2024-05-20
      "endDate": <string>, // date string e.g.: 2024-05-20
      "boost": <string>, // decimal string
      "totalPoints": <string>, // big number string
      "totalBoostedPoints": <string> // decimal string
    }
  ]
}
```

What do you think? cc/ @moisses89 @safe-global/safe-client-gateway-maintainers @schmanu

**Comment by fmrsabino** [comment]
As an update on the previous proposal. What do you think of the following one?

```javascript
GET /api/v1/campaigns/<uuid:resource_id>/activities/?holder=<address>

{
  "count": <number>,
  "next": <url>, // nullable
  "previous": <url>,  // nullable
  "results": [
    {
      "startDate": <string>, // date string e.g.: 2024-05-20
      "endDate": <string>, // date string e.g.: 2024-05-20
      "holder": <string>, // Holder's address
      "boost": <string>, // decimal string
      "totalPoints": <string>, // big number string
      "totalBoostedPoints": <string> // decimal string
    }
  ]
}
```

This is more in line with the resource hiearchy that we have in place. Without indexing any `Period`, we are just left with `Activities`. We can then apply a filter on the collection of `Activities` for a given `Campaign` by setting the `holder` query parameter.

This is what is currently proposed in https://github.com/safe-global/safe-locking-service/pull/137

**Comment by JagoFigueroa** [comment]
Hola team, question. Was the endpoint added to Swagger? I cannot seem to find it [here](https://safe-locking-sepolia.staging.5afe.dev/) 🤔

**Comment by JagoFigueroa** [comment]
Otherwise todo bueno. Un saludito

**Comment by fmrsabino** [comment]
> Hola team, question. Was the endpoint added to Swagger? I cannot seem to find it [here](https://safe-locking-sepolia.staging.5afe.dev/) 🤔

The endpoint is there but it's missing the `holder` query parameter (which can be used). I will work on a fix for it.

**Comment by fmrsabino** [comment]
Query parameter was added to the Swagger interface in https://github.com/safe-global/safe-locking-service/pull/140

**Comment by fmrsabino** [comment]
> Query parameter was added to the Swagger interface in #140

PR was merged. `holder` query param is now available in the Swagger interface.
