### ISSUE TITLE
Add campaign fields

### ISSUE THREAD

**Issue by moisses89** [safe-global/safe-locking-service#168]
# What is needed?
We would like to add new campaign fields to database model, and return them accordingly in the endpoint view.
New campaign fields: 
`rewardValue` - number eg: 600,000
`rewardText` - string e.g. "Some text description of reward"
`iconUrl` - string
`safeAppUrl` -  string
`partnerUrl` -  string

`iconUrl` should return the stored icon link and the admin page must support upload an icon per campaign.
All the previous fields can be nullable

**Comment by falvaradorodriguez** [comment]
At the request of @schmanu, an `isPromoted` field is also added, with boolean value and default value `False`.

**Comment by JagoFigueroa** [comment]
Testeado y verificado. Un saludo 🙇
