### ISSUE TITLE
Add admin view to upload the Activities CSV File

### ISSUE THREAD

**Issue by moisses89** [safe-global/safe-locking-service#81]
# What is needed?
Create a view in the admin page with a formulary to upload the CSV file with the Activity results.
After the upload the file should be processed and stored in the database.

**Comment by fmrsabino** [comment]
I was considering tackling this issue in two separate chunks of work:

1. Uploading of the file
  * Here I would do minimal validation or no validation at all (of the CSV headers if any).
  * This would depend on how restrictive we want to be with the file upload.
2. Upon upload, schedule a task to process the file and create new database entries for the activity
  * On completion, mark the file as processed.

I think it's important to keep a registry of all the files uploaded so far and generate the respective entries without overriding entries that were previously generated. This allows us to keep a record of the activity that was provided by each file.

**Comment by moisses89** [comment]
Do you think that would be necessary to store the raw CSV file? 
I mean, run the parser in a scheduled task requires to have the file in any place.

**Comment by fmrsabino** [comment]
> Do you think that would be necessary to store the raw CSV file? I mean, run the parser in a scheduled task requires to have the file in any place.

I would consider storing it securely on an external storage (e.g.: S3 bucket) and after uploading the file trigger a task to process it.

We can have admin actions to reprocess the file in case something goes wrong without requiring a new upload.
